# Generated by Django 4.2.3 on 2023-08-14 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0004_catrgory_post_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catrgory',
            new_name='Category',
        ),
    ]
